name: Bare Maximum
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73382
title: Bare Maximum - Pushing the Paradigm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#93b630'
    - '#829ca0'
    - '#000000'
    - '#808080'
    - '#718e8e'
  brandStrength: 0.75
  lightness: 0.20856494852341712
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
