name: Bare Maximum
favicon: null
layout_spectrum: 0.5688521857373416
typography_spectrum: 0.4235264484304935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.275269455043599
  lightness: 0.20856494852341712
  saturation: 0.36076972587034106
  rhythmicContrast: 0.6241861467715353
purpose: []
